### ISSUE TITLE
keymaps for insert mode

### ISSUE THREAD

**Issue by m-faith** [Myzel394/easytables.nvim#1]
Excited to learn of this plugin! Regarding https://www.reddit.com/r/neovim/comments/1735zf6/comment/k41b2l6 and the question about keymaps for insert mode:

I think `tab` (and `shift`+`tab`) would be great for going right (and left) a cell with `enter` for down (and `shift`+`enter` for up).

Someone there recommend ctrl + hjkl but that conflicts with common tmux bindings for pane and window navigation. So if you chose to go with those, hopefully it will be configurable :)

**Comment by Myzel394** [comment]
@m-faith easytables is completely configurable! :D You will need to override `set_mappings`, see [configuration](https://github.com/Myzel394/easytables.nvim#default-configuration) for more

**Comment by m-faith** [comment]
Awesome! And thanks for pointing out what I missed in the readme!!!
