### ISSUE TITLE
How to export the table? 

### ISSUE THREAD

**Issue by anoduck** [Myzel394/easytables.nvim#5]
So, this is awesome. I write a lot of tables in markdown for my personal notes, and this is SO much easier. I just have one very stupid question. Once you have finished editing the table in the preview, how do you get it to insert the table onto the page?

**Comment by Myzel394** [comment]
Haha no worries :D I'm on mobile but the command should be like `EasyTablesExportTable` or something like that.

Note that I do plan to rewrite the whole project at one point, making it much easier and more intuitive to work with (for example you'll be able to export the table using 'write'), but that's gonna take some time first

**Comment by anoduck** [comment]
The command `:EasyTablesImportThisTable` is the closest one available, and it didn't work. I used `Lazy.nvim` to install it, and it hasn't been the smoothest of integrations. I will probably need to wait until the next release. It does show promise over what else is out there.

Thanks for the response, stay cool out there.

**Comment by uwla** [comment]
Once you are in the preview mode, the command is `Export`
